### PR TITLE
Upgrade QUnitJS from 1.10.0 to 1.23.1

### PR DESCRIPTION
**Pull request by yomexzo**
Hi, @minasmart

Kindly help review the changes here to `node-qunit` before I create a PR into [kof/node-qunit](https://github.com/kof/node-qunit)

cc @kof

### CODE REVIEW

**Comment by yomexzo** [comment]
cc @tessalt

**Comment by yomexzo** [comment]
cc @jzaefferer

**Comment by minasmart** [comment]
Why wast `test` a global before, and now nested under the QUnit global? Is there an assignment missing somewhere?

**Comment by yomexzo** [comment]
@minasmart, `test` is still available actually. I felt being explicit is better.

**Comment by minasmart** [comment]
The PR should have a single purpose. If the purpose is to support qunit 1.20, then do that. If you want it to be more explicit (which is fine), that's a separate PR. One thing is an enhancement, the other is an opinionated choice that the maintainer may or may not be for. 😄

**Comment by yomexzo** [comment]
true! 😄 .. updating ...

**Comment by yomexzo** [comment]
updated @minasmart. Thanks! 😸

**Comment by minasmart** [comment]
Looks good 👍

**Pull request merged**
